/* eslint-disable @typescript-eslint/indent */

import { UniversalPageProps } from './universal-page-props';

/**
 * Dynamic (server) properties returned by getInitialProps or getServerProps for server-side rendered pages (using SSR)
 * Mind that those properties are generated by the server, for each request
 *
 * Multiversal page props are listed in MultiversalPageProps
 * Server-side page props are listed in SSRPageProps
 * Client-side page props are listed in SSGPageProps
 */
export type SSRPageProps<E = any> = {
  // Props that are specific to SSR
  isServerRendering: boolean;
} & UniversalPageProps & // Generic props that are provided immediately, no matter what
  E;
